version: '3.9'
services:

  db:
    image: mariadb:10.7.4
    restart: always
    environment:
      MYSQL_DATABASE: microservice
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33066:3306"
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8000"
    volumes:
      - .:/app
    depends_on:
      - db
